"use strict";

exports.httpCodes = {
    "HTTP_OK": 200,
    "HTTP_CREATED": 201,
    "HTTP_ACCEPTED": 202,
    "HTTP_NO_CONTENT": 204,
    "HTTP_NOT_MODIFIED": 304,
    "HTTP_BAD_REQUEST": 400,
    "HTTP_UNAUTHORIZED": 401,
    "HTTP_FORBIDDEN": 403,
    "HTTP_NOT_FOUND": 404,
    "HTTP_METHOD_NOT_ALLOWED": 405,
    "HTTP_PRECONDITION_FAILED": 412,
    "HTTP_UNSUPPORTED_MEDIA_TYPE": 415,
    "HTTP_INTERNAL_SERVER_ERROR": 500,
    "HTTP_SERVICE_UNAVAILABLE": 503
};
